name: Yolo5 Microservice Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

      - name: Login to docker
        env: 
          DOCKER_USR: ${{secrets.DOCKER_USR}}
          DOCKER_PWD: ${{secrets.DOCKER_PWD}}
        run: echo "$DOCKER_PWD" | docker login --username $DOCKER_USR --password-stdin

      - name: Checkout the repo code
        uses: actions/checkout@v3
        
      - name: Docker Build
        run: docker build -t /yolo5 

      - name: Docker Tag
        run: docker tag yolov5 keretdodor/yolov5
      
      - name: Docker Push
        run: docker push keretdodor/yolov5:latest

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Deploy new version
        run: |         
          # TODO your implementation here....     
     
